version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/src
    command: node .
    restart: unless-stopped
    mem_limit: "1g"
    mem_reservation: "512m"
    cpus: "1"
    cpuset: "2"
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    ports:
      - "30001:3000"
    environment:
      NODE_ENV: production
      DEBUG: nodejs-docker-express:*
